version: '3.8'

services:
  # האפליקציה שלך
  api:
    image: itai1989/node-sql-app:latest
    ports:
      - "3003:3000"
    restart: always
    environment:
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=mysecret
      - DB_NAME=mydb
    depends_on:
      - mysql_db

  # הדאטה בייס
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: